DELETE FROM usuarios;
INSERT INTO usuarios (nombre, usuario, password, rol, email) VALUES 
    ('Administrador Sistema', 'admin', 'admin', 'admin', 'admin@sistema.com'),
    ('Rodrigo Bustamante', 'disenador', 'disenador', 'disenador', 'disenador@sistema.com'),
    ('Luis Ignacio Carreño', 'dibujante', 'dibujante', 'dibujante', 'dibujante@sistema.com'),
    ('Victor Corona', 'supervisor', 'supervisor', 'supervisor', 'supervisor@sistema.com'),
    ('Implementador San Fernando', 'impl_sf', 'impl_sf', 'implementador', 'sf@sistema.com'),
    ('Implementador Rengo', 'impl_rengo', 'impl_rengo', 'implementador', 'rengo@sistema.com'),
    ('Implementador Las Cabras', 'impl_cabras', 'impl_cabras', 'implementador', 'cabras@sistema.com'),
    ('Implementador Coltauco', 'impl_coltauco', 'impl_coltauco', 'implementador', 'coltauco@sistema.com'),
    ('Implementador Requinoa', 'impl_requinoa', 'impl_requinoa', 'implementador', 'requinoa@sistema.com'),
    ('Implementador Chépica', 'impl_chepica', 'impl_chepica', 'implementador', 'chepica@sistema.com'),
    ('Implementador Peralillo', 'impl_peralillo', 'impl_peralillo', 'implementador', 'peralillo@sistema.com'),
    ('Implementador Pichilemu', 'impl_pich', 'impl_pich', 'implementador', 'pich@sistema.com'),
    ('Implementador Hualañé', 'impl_hualane', 'impl_hualane', 'implementador', 'hualane@sistema.com'),
    ('Implementador Quinta de Tilcoco', 'impl_tilcoco', 'impl_tilcoco', 'implementador', 'tilcoco@sistema.com'),
    ('Implementador Nancagua', 'impl_nancagua', 'impl_nancagua', 'implementador', 'nancagua@sistema.com'),
    ('Implementador Chanco', 'impl_chanco', 'impl_chanco', 'implementador', 'chanco@sistema.com'),
    ('Implementador Villa Alegre', 'impl_valegre', 'impl_valegre', 'implementador', 'valegre@sistema.com'),
    ('Implementador Colbún', 'impl_colbun', 'impl_colbun', 'implementador', 'colbun@sistema.com'),
    ('Implementador Teno', 'impl_teno', 'impl_teno', 'implementador', 'teno@sistema.com'),
    ('Implementador Yerbas Buenas', 'impl_ybuenas', 'impl_ybuenas', 'implementador', 'ybuenas@sistema.com'),
    ('Implementador Longaví', 'impl_longavi', 'impl_longavi', 'implementador', 'longavi@sistema.com'),
    ('Implementador Maule', 'impl_maule', 'impl_maule', 'implementador', 'maule@sistema.com');
