INSERT INTO sucursales (nombre) VALUES 
    ('San Fernando'),
    ('Rengo'),
    ('Las Cabras'),
    ('Coltauco'),
    ('Requinoa'),
    ('Chépica'),
    ('Peralillo'),
    ('Pichilemu'),
    ('Hualañé'),
    ('Quinta de Tilcoco'),
    ('Nancagua'),
    ('Chanco'),
    ('Villa Alegre'),
    ('Colbún'),
    ('Teno'),
    ('Yerbas Buenas'),
    ('Longaví'),
    ('Maule');
